/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2015-10-29 10:35:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cn.hofan.dal.impl.SupplierDaoImpl;

public final class bind_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write(" \n");
      out.write("<!-- 公共HEAD设置 -->\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<title>账号绑定</title>\n");
      out.write("<meta name=\"description\" content=\"浩方 供应商 门户 账号绑定\" />\n");
      out.write("<meta name=\"keywords\" content=\"浩方 供应商 门户 账号绑定\" />\n");
      out.write("<meta name=\"robots\" content=\"INDEX,FOLLOW\" />\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=7\" />\n");
      out.write("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n");
      out.write("<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\n");
      out.write("<meta name=\"apple-mobile-web-app-title\" content=\"\">\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=no\">\n");
      out.write("<!-- <meta id=\"viewport\" name=\"viewport\" content=\"width=640px,minimum-scale=0.2,maximum-scale=0.2\" /> --> \n");
      out.write("<!-- <meta id=\"viewport\" name=\"viewport\" content=\"width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0\" />-->\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\"/>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--[if lte IE 9]>\n");
      out.write("<script type=\"text/javascript\" src=\"http://www.100what.com/media/js/eff9c204dba7cd1c4ae36bc4db1a7848.1442479459.js\"></script>\n");
      out.write("<![endif]-->\n");
      out.write("\n");
      out.write("<!-- 苹果设备ViewPort兼容 -->\n");
      out.write("<!-- <script type=\"text/javascript\">\n");
      out.write("\tif (/(iPhone|iPad|iPod|iOS)/i.test(navigator.userAgent)) {\n");
      out.write("\t\t//alert(navigator.userAgent); \n");
      out.write("\t\t//add a new meta node of viewport in head node\n");
      out.write("\t\thead = document.getElementsByTagName('head');\n");
      out.write("\t\tviewport = document.createElement('meta');\n");
      out.write("\t\tviewport.name = 'viewport';\n");
      out.write("\t\tviewport.content = 'target-densitydpi=device-dpi, width=' + 640 + 'px, user-scalable=no';\n");
      out.write("\t\thead.length > 0 && head[head.length - 1].appendChild(viewport);    \n");
      out.write("\t\t   \n");
      out.write("\t}\n");
      out.write("</script> -->\n");
      out.write("\n");
      out.write("<!-- 微信JS API -->\n");
      out.write("<script src=\"http://res.wx.qq.com/open/js/jweixin-1.0.0.js\"></script>\n");
      out.write("<script>\n");
      out.write("  \twx.config({\n");
      out.write("\t    debug: false,\n");
      out.write("\t    appId: 'wxbe3a2665ec44da5e',\n");
      out.write("\t    timestamp: 1442912946,\n");
      out.write("\t    nonceStr: 'MUv9cDZOW4F5txMN',\n");
      out.write("\t    signature: 'f53e6a4df3ee6dd70cd9ee88aceb665408389cc8',\n");
      out.write("\t    jsApiList: [\n");
      out.write("\t        'checkJsApi',\n");
      out.write("\t        'onMenuShareTimeline',\n");
      out.write("\t        'onMenuShareAppMessage',\n");
      out.write("\t        'showMenuItems',\n");
      out.write("\t        'hideMenuItems',\n");
      out.write("// \t        'chooseWXPay',\n");
      out.write("\t\t]\n");
      out.write("  \t});\n");
      out.write("</script>\n");
      out.write("<script src=\"http://www.100what.com/skin/frontend/aw_mobile/iphone/js/wxjsapi.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction OnInput(event){\n");
      out.write("\t\tdocument.getElementById(\"butt\").disabled=false;\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body  class=\"weixin-home-index\">\n");

request.setCharacterEncoding("UTF-8");
String openid = request.getParameter("openid");
//out.print("openid="+openid);
SupplierDaoImpl dao = new SupplierDaoImpl();
if(!dao.openIdIsChecked(openid)){
	if(dao.openIdCheckedExpire(openid)){

      out.write("\n");
      out.write("\t<div class=\"wrap\" align=\"center\"  style=\"background:url(bg.jpg) no-repeat ; background-size: cover; -moz-background-size: cover; \" > \n");
      out.write("\t\t<form action=\"http://weixin.hofan.cn/weixin/bind2.jsp?openid=");
      out.print(openid);
      out.write("\" method=\"post\">\n");
      out.write("\t\t<br><br>\n");
      out.write("\t\t<div>验证超时,请重新输入供应商编号</div><br><br>\n");
      out.write("\t\t\t<input style=\"border-radius:5px;width:300px;height:35px\" type=\"text\" name=\"erpcode\" oninput=\"OnInput(event)\" placeholder=\"请重新输入您的供应商编号\"/><br><br><br>\n");
      out.write("\t\t\t<input style=\"border-radius:5px;width:300px;height:50px;background:green;color: white;font-size: 20px\" id=\"butt\" type=\"submit\" name=\"secondname\"  disabled=\"disabled\"  value=\"发送验证码\"/><br><br><br>\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write(" \t\n");
      out.write("\t\n");

	}else if(!dao.openIdIsNotChecked(openid)){
		
      out.write("\n");
      out.write("\t\t<div class=\"wrap\" align=\"center\"  style=\"background:url(bg.jpg) no-repeat ; background-size: cover; -moz-background-size: cover; \" > \n");
      out.write("\t\t<form action=\"http://weixin.hofan.cn/weixin/bind2.jsp?openid=");
      out.print(openid);
      out.write("\" method=\"post\">\n");
      out.write("\t\t<div><br><br><b>供应商编号</b><br><br></div>\n");
      out.write("\t\t\t\t<input style=\"border-radius:5px;width:300px;height:35px\" type=\"text\" oninput=\"OnInput(event)\" name=\"erpcode\" placeholder=\"请输入您的供应商编号\"/><br><br>\n");
      out.write("\t\t\t\t<input style=\"border-radius:5px;width:300px;height:50px;background:green;color: white;font-size: 20px\" id=\"butt\" disabled=\"disabled\" type=\"submit\" name=\"secondname\"  value=\"发送验证码\"/><br><br><br><br>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");

	}else{
		String erpcode = dao.getCode(openid);
		
      out.write("\n");
      out.write("\t\t<div class=\"wrap\" align=\"center\" style=\"background:url(bg.jpg) no-repeat ; background-size: cover; -moz-background-size: cover; \">\n");
      out.write("\t\t<form\n");
      out.write("\t\t\taction=\"http://weixin.hofan.cn/weixin/bindanswer.jsp?openid=");
      out.print(openid);
      out.write("\"\n");
      out.write("\t\t\tmethod=\"post\">\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<div>请您前往浩方门户绑定的邮箱收发验证码</div>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br> <input\n");
      out.write("\t\t\t\tstyle=\"border-radius: 5px; width: 300px; height: 35px\" type=\"text\"\n");
      out.write("\t\t\t\tname=\"firstname\" oninput=\"OnInput(event)\" placeholder=\"请输入验证码\" /><br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br> <input\n");
      out.write("\t\t\t\tstyle=\"border-radius: 5px; width: 300px; height: 50px; background: green; color: white; font-size: 20px\"\n");
      out.write("\t\t\t\tid=\"butt\" disabled=\"disabled\" type=\"submit\" name=\"secondname\"\n");
      out.write("\t\t\t\tvalue=\"提交\" /> <input type=\"hidden\" name=\"erpcode\"\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(erpcode);
      out.write("\" /><br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");

	}
	
}else{
	
      out.write("\n");
      out.write("\t<div class=\"wrap\" align=\"center\" style=\"background:url(bg.jpg) no-repeat ; background-size: cover; -moz-background-size: cover; \">\n");
      out.write("\t\t<br><br><br><br><div><b>账号已绑定！</b></div><br><br><br><br>\n");
      out.write("\t</div>\n");
      out.write("\t");

}

      out.write("\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
