/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2015-10-29 10:35:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import net.sf.json.JSONObject;
import cn.hofan.util.FileUtil;
import java.io.File;
import cn.hofan.util.WeixinUtil;
import cn.hofan.dal.impl.SupplierDaoImpl;

public final class bindanswer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<!-- <meta id=\"viewport\" name=\"viewport\" content=\"width=640px,minimum-scale=0.2,maximum-scale=0.2\" /> -->\n");
      out.write("<!-- <meta id=\"viewport\" name=\"viewport\" content=\"width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0\" />-->\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("<title>绑定结果</title>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction OnInput(event){\n");
      out.write("\t\tdocument.getElementById(\"butt\").disabled=false;\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#fenge {\n");
      out.write(" height:1px;\n");
      out.write(" width:100%;\n");
      out.write(" background:#999999;\n");
      out.write(" overflow:hidden;\n");
      out.write(" }\n");
      out.write(" .divcss5-bottom{ margin-top:10px}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"wrap\" align=\"center\" style=\"background:url(bg.jpg) no-repeat ; background-size: cover; -moz-background-size: cover; \">\n");
      out.write("\t\t");

		    request.setCharacterEncoding("UTF-8");
			String erpcode = request.getParameter("erpcode");
			String url = request.getHeader("Referer");
			String openid = url.substring(url.indexOf("=") + 1);
			String yanzhengma = request.getParameter("firstname");
			long time = System.currentTimeMillis();

			SupplierDaoImpl dao = new SupplierDaoImpl();
			String yanzhengcode = dao.getYanzhengma(erpcode, openid);
			if (yanzhengcode.equals(yanzhengma)) {
				if (((time - dao.getsenddate(erpcode, openid)) / (1000 * 60)) < 30) {
			    //	out.print("<br><br>openid=" + openid);
				//	out.print("<br>erpcode=" + erpcode);
				//	out.print("<br>yanzhengma=" + yanzhengma);
					out.print("<br><br>绑定成功！绑定账号：" + erpcode+"<br><br><br><br>");
					dao.setYanzhengExpire(erpcode, openid, yanzhengcode, 0l, 1);
					File file = new File("/opt/soft/tomcat_weixin/webapps/accesstoken.txt");
					String accesstoken = null;
					try {
						accesstoken = FileUtil.readTxtFile(file);
						System.out.println("从/opt/soft/tomcat_weixin/webapps/accesstoken.txt中读出accesstoken成功: "+accesstoken);
					} catch (Exception e) {
						System.out.println("从/opt/soft/tomcat_weixin/webapps/accesstoken.txt中读出accesstoken出错: "+e);
					}
					String requestUrl = "https://api.weixin.qq.com/cgi-bin/groups/members/update?access_token="+accesstoken+"";
					String body = "{\"openid\":\""+openid+"\",\"to_groupid\":2}";
					JSONObject jsonObject = WeixinUtil.httpRequest(requestUrl, "POST", body);
					if (null != jsonObject) {  
			            if (0 != jsonObject.getInt("errcode")) {  
							System.out.println("移动"+erpcode+"到星标组失败 errcode:{"+jsonObject.getInt("errcode")+"} errmsg:{"+jsonObject.getString("errmsg")+"}");
			            }else {
							System.out.println("移动"+erpcode+"到星标组成功");
						}  
			        } 
				} else {
					dao.setYanzhengExpire(erpcode, openid, yanzhengcode, 0l, 2);
		
      out.write("\n");
      out.write("\t\t<div class=\"wrap\" align=\"center\" >\n");
      out.write("\t\t\t<form\n");
      out.write("\t\t\t\taction=\"http://weixin.hofan.cn/weixin/bind2.jsp?openid=");
      out.print(openid);
      out.write("\"\n");
      out.write("\t\t\t\tmethod=\"post\">\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<div>验证超时,请您重新输入供应商编号:</div>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<br> <input\n");
      out.write("\t\t\t\t\tstyle=\"border-radius: 5px; width: 300px; height: 30px\" type=\"text\"\n");
      out.write("\t\t\t\t\tname=\"erpcode\" oninput=\"OnInput(event)\" placeholder=\"请重新输入您的供应商编号\" /><br>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<br> <input\n");
      out.write("\t\t\t\t\tstyle=\"border-radius: 5px; width: 300px; height: 50px; background: #green; color: white; font-size: 20px\"\n");
      out.write("\t\t\t\t\tid=\"butt\" type=\"submit\" name=\"secondname\" disabled=\"disabled\"\n");
      out.write("\t\t\t\t\tvalue=\"发送验证码\" /><br>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");

			}
			} else {
				//out.print("<br><br>openid=" + openid);
				//out.print("<br>erpcode=" + erpcode);
				//out.print("<br>yanzhengma=" + yanzhengma);
				out.print("<br><br>供应商编号为 " + erpcode
						+ "<br><br>但输入的验证码不正确，账号绑定失败！<br><br><br>");

			}

			/*
			 //驱动程序名   
			 String driverName = "com.mysql.jdbc.Driver";  
			 //数据库用户名   
			 String userName = "root";  
			 //密码   
			 String userPasswd = "12345678";  
			 //数据库名   
			 String dbName = "sp_db";  
			 //表名   
			 String tableName = "weixin_info";  
			 //联结字符串   
			 String url = "jdbc:mysql://192.168.3.77:3306/" + dbName + "?user="  
			 + userName + "&password=" + userPasswd;  
			 Class.forName("com.mysql.jdbc.Driver").newInstance();  
			 Connection connection = DriverManager.getConnection(url);  
			 Statement statement = connection.createStatement();  
			 String sql = "SELECT isemailchecked from "+tableName+" where openid='"+fromUserName+"'";  
			 ResultSet rs = statement.executeQuery(sql);  
			 if(){
			
			 }
			 */
		
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<br>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
