/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2015-06-16 12:52:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.communication;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CommunicationHandle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1423467176000L));
    _jspx_dependants.put("jar:file:/opt/web/csma/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var bspUrl = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bspUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("document.domain=\"hofan.cn\";\r\n");
      out.write("</script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>沟通处理</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }/views/RefundHeader.html", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.1/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.1/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.1/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/js/iframeproxy.js\"></script> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/js/kindeditor/themes/default/default.css\" />\r\n");
      out.write("<script charset=\"utf-8\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/js/kindeditor/kindeditor-min.js\"></script>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/amazonmenu.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<script charset=\"utf-8\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/amazonmenu.js\"></script>\r\n");
      out.write("<script charset=\"utf-8\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/communication/CommunicationHandle.js\"></script> \t\r\n");
      out.write("<script charset=\"utf-8\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scroll/scroll.js\"></script>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scroll/scrollcss.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/CommonHandle.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/search/searchwindow.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".filterTable td{\r\n");
      out.write("\t\theight: 25px;\r\n");
      out.write("\t}\r\n");
      out.write(".divcss5{height:300px; border:1px solid gray; overflow:auto}\r\n");
      out.write(".detaila{\r\n");
      out.write("\tcolor: blue;\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write(".orderTable{\r\n");
      out.write("\tborder: 1px solid #D3D3D3;\r\n");
      out.write("\twidth: 100%; \r\n");
      out.write("\tmargin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write(".orderTable td{\r\n");
      out.write("\tborder-top: 1px solid #D3D3D3;\r\n");
      out.write("\tborder-bottom: 1px solid #D3D3D3;\r\n");
      out.write("\theight: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".messageContentAll{\r\n");
      out.write(" \toverflow: scroll;\r\n");
      out.write(" \tmargin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".headerStyle{\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}    \r\n");
      out.write("\r\n");
      out.write(".orderTd{\r\n");
      out.write("\twidth:0; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".orderTdDis{\r\n");
      out.write("\twidth: 40%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".messageTd{\r\n");
      out.write("\twidth: 99%;\r\n");
      out.write("\tpadding-left: 5px;\r\n");
      out.write("}\r\n");
      out.write(".messageTdDis{\r\n");
      out.write("\twidth: 60%;\r\n");
      out.write("\tpadding-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"body1\">\r\n");
      out.write("<div align=\"center\" style=\"width: 100%;margin-top: 5px;\">\r\n");
      out.write("\t<div class=\"easyui-layout\" id=\"messgeLayout\" style=\"width:100%;height:1000px;padding:0px;margin:0px;\">\r\n");
      out.write("        <div data-options=\"region:'west',split:true\" style=\"width:43%;\" title=\"订单查询\" >\r\n");
      out.write("\t\t\t<iframe id=\"orderInfoDetailFrame\" name=\"orderInfoDetailFrame\" \r\n");
      out.write("\t\t\t\tstyle=\"width: 100%;height: 100%;\" frameborder=\"0\"></iframe>\r\n");
      out.write("        </div>\t\r\n");
      out.write("        <div data-options=\"region:'center'\" style=\"width:100%;padding:0px;margin:0px;\" align=\"center\">\r\n");
      out.write("\t\t\t<div align=\"center\" id=\"MessageContent\" class=\"easyui-panel\" title=\"沟通消息\" style=\"width: 100%;height: 100%;\">\r\n");
      out.write("\t\t\t\t<div id=\"updown\"><span class=\"up\"></span><span class=\"down\"></span></div>\r\n");
      out.write("\t\t\t\t<div align=\"left\" style=\"padding: 5px 0px 5px 15px;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" onClick=\"nextSiteMessage()\" style=\"color: #000\">下一条</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" onClick=\"writeEmail()\" style=\"color: #000\">撰写邮件</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-back'\" onClick=\"backPendingTask()\" style=\"color: #000\">返回待处理</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"dynamicContent\">\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t   \t<div id=\"comm\" class=\"easyui-panel\" title=\"当前沟通记录\" \r\n");
      out.write("\t\t\t   \t\tdata-options=\"iconCls:'icon-save',collapsible:true\" style=\"width: 97%;height: 320px;\">\r\n");
      out.write("\t\t\t\t\t<table style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t   <tr ondblclick=\"showMesDiv(this,");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.rcSitemessageid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",0);\">\r\n");
      out.write("\t\t\t\t\t\t      <td>\r\n");
      out.write("\t\t\t\t\t\t      <!-- 消息title信息 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"font-family: '应用字体 Regular', '应用字体'; font-weight: 400;\"> ~~ ~~ ~~Buyer~~ ~~ ~~");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.rcSendingUserID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ~~ ~~ ~~");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.rcDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("~~ ~~ ~~<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/communicate/showMessageAll?siteMessageId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.rcSitemessageid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" target=\"_bank\"  class=\"detaila\">查看详细</a>~~ ~~ ~~ ~~  ~~ ~~ ~~ ~~ ~~ ~~</span><br/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span style=\"font-family: '应用字体 Regular', '应用字体'; font-weight: 400;\"><b>主旨：</b></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span style=\"font-family: '应用字体 Regular', '应用字体'; font-weight: 400;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.subject}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t      <!-- 消息body信息 -->\r\n");
      out.write("\t\t\t\t\t\t      ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.rcBody}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t      <!-- 消息页脚信息 -->\r\n");
      out.write("\t\t\t\t\t\t            <p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-family: '应用字体 Regular', '应用字体'; font-weight: 400;\">--------------------------------------------------------------------------------------------</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-family: '应用字体 Regular', '应用字体'; font-weight: 400;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.rcbottom}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-family: '应用字体 Regular', '应用字体'; font-weight: 400;\">--------------------------------------------------------------------------------------------</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t\t\t  \t <td>附件：</td>\r\n");
      out.write("\t\t\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t\t\t   \t<td>\r\n");
      out.write("\t\t\t\t\t\t   \t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t   \t</td>\r\n");
      out.write("\t\t\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t\t</table> \r\n");
      out.write("\t\t\t   \t</div>\r\n");
      out.write("\t\t\t   \t<div style=\"height: 5px;\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"commAfter\" class=\"easyui-panel\" title=\"历史沟通记录\" \r\n");
      out.write("\t\t\t   \t\tdata-options=\"iconCls:'icon-save',collapsible:true,collapsed:true,onBeforeExpand:searchAfterMessage\" style=\"width: 97%;\">\r\n");
      out.write("\t\t\t   \t\t<div id=\"hisTabs\" class=\"easyui-tabs\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t   \t\t\t<input type=\"hidden\" id=\"hisTabs_flag\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t<div id=\"sameOrder\" title=\"同订单沟通记录\" style=\"padding:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<iframe id=\"sameOrderFrame\" name=\"sameOrderFrame\" width=\"100%\" frameborder=\"0\"></iframe>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"easyui-pagination\" id=\"sameOrderPagination\" data-options=\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttotal: 0,\r\n");
      out.write("\t\t\t\t\t\t\t\tpageSize:2,pageList:[2,50,100],pageNumber:1,\r\n");
      out.write("\t\t\t\t\t\t\t\tonSelectPage:searchHisMessage,\r\n");
      out.write("\t\t\t\t\t\t\t\tshowRefresh: false,\r\n");
      out.write("\t\t\t\t\t\t\t\tdisplayMsg: ''\r\n");
      out.write("\t\t\t\t\t\t\t\" style=\"margin-top: 5px;margin-bottom: 5px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"sameCustom\" title=\"同客户沟通记录\" style=\"padding:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<iframe id=\"sameCustomFrame\" name=\"sameCustomFrame\" width=\"100%\" frameborder=\"0\"></iframe>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"easyui-pagination\" id=\"sameCustomPagination\" data-options=\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttotal: 0,\r\n");
      out.write("\t\t\t\t\t\t\t\tpageSize:2,pageList:[2,50,100],pageNumber:1,\r\n");
      out.write("\t\t\t\t\t\t\t\tshowRefresh: false,\r\n");
      out.write("\t\t\t\t\t\t\t\tonSelectPage:searchHisMessage,\r\n");
      out.write("\t\t\t\t\t\t\t\tdisplayMsg: ''\r\n");
      out.write("\t\t\t\t\t\t\t\" style=\"margin-top: 5px;margin-bottom: 5px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t   \t</div>\r\n");
      out.write("\t\t\t   \t\r\n");
      out.write("\t\t\t   \t<!-- 模板选择*************************************************** -->\r\n");
      out.write("\t\t\t\t<div style=\"height: 5px;\"></div>\r\n");
      out.write("\t\t\t   \t<div id=\"templateSelect\" class=\"easyui-panel\" title=\"消息回复\" \r\n");
      out.write("\t\t\t   \t\tdata-options=\"iconCls:'icon-save',collapsible:true\" style=\"width: 97%;margin-bottom: 5px;\">\r\n");
      out.write("\t\t\t\t\t<table style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\" style=\"height: 30px;\"><label class=\"control-label\">选择模板：</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea id=\"editLanguage\" name=\"editLanguage\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVo.description }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\" align=\"center\" style=\"padding-top: 5px;padding-bottom: 5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" onClick=\"writeEmail()\" style=\"width:100px;\">撰写邮件</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write(" \t<!-- 绑定订单号层，无需处理，删除对应div -->\r\n");
      out.write("\t<div class=\"popover fade right in\"\r\n");
      out.write("\t\tstyle=\"top: 143.5px; display: none;width: 450px;z-index: 9999;position: absolute;\" id=\"divLanguage\">\r\n");
      out.write("\t\t<div class=\"arrow\"></div>\r\n");
      out.write("\t\t<div class=\"popover-inner\">\r\n");
      out.write("\t\t\t<div class=\"popover-content\">\r\n");
      out.write("\t\t\t\t<form class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"关闭\" src=\"/images/close_normal.png\" \r\n");
      out.write("\t\t\t\t\t\t\tonmouseout=\"javascript:this.src='/images/close_normal.png'\"\r\n");
      out.write("\t\t\t\t\t\t\tonmouseover=\"javascript:this.src='/images/close_over.bmp'\" \r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"hideDivLanguage()\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"关闭\" style=\"cursor: pointer;position: absolute;float: right;top: 0px;right: 0px;\"/>\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-group;\" id=\"btnDiv\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-remove'\" onClick=\"delMessage()\" style=\"color: #000\">删除</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-ok'\" onClick=\"noDealMessage()\" style=\"color: #000\">无需处理</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-ok'\" onClick=\"showUpMesLgDiv()\" style=\"color: #000\">更改语言</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-ok'\" onClick=\"saveCustomType()\" style=\"color: #000\">自定义类别</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label class=\"control-label\">客户账号：</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"sendingUserIdDiv\" name=\"sendingUserIdDiv\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-mini\" value=\"绑\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-mini\" value=\"x\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-mini\" value=\"查\" onclick=\"searchOrderByBuyerAccount()\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label class=\"control-label\">客户邮址：</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"\" name=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-mini\" value=\"绑\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-mini\" value=\"x\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-mini\" value=\"查\" />\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label class=\"control-label\">订单号：</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"orderIdDiv\" name=\"orderIdDiv\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-mini\" onclick=\"bindingOrder('Yes')\" value=\"绑\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-mini\" onclick=\"bindingOrder('No')\" value=\"x\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-mini\" onclick=\"searchOrder()\" value=\"查\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label class=\"control-label\">技术支持：</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"itemIdDiv\" name=\"itemIdDiv\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.itemId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-mini\" value=\"绑\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-mini\" value=\"x\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-mini\" onclick=\"technicalSupport()\" value=\"查\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label class=\"control-label\">产品详情：</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"itemIdDiv1\" name=\"itemIdDiv1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.itemId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-mini\" value=\"绑\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-mini\" value=\"x\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-mini\" onclick=\"searchProductInfo()\" value=\"查\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write(" \t\r\n");
      out.write(" \t<!-- 隐藏表单  临时存储语言Id 用于获取模板的时候 -->\r\n");
      out.write("\t<input type=\"hidden\" id=\"siteMessageId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.rcSitemessageid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t<input type=\"hidden\" id=\"orderId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.rcOrderId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><!-- 订单号 -->\r\n");
      out.write("\t<input type=\"hidden\" id=\"transactionId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.rcOrderId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><!-- 订单号 -->\r\n");
      out.write("\t<input type=\"hidden\" id=\"sendingUserId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.rcSendingUserID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><!-- 客户号 -->\r\n");
      out.write("\t<input type=\"hidden\" id=\"buyerId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.rcSendingUserID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><!-- 客户号 -->\r\n");
      out.write("\t<input type=\"hidden\" id=\"account\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.account }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><!-- 账号 -->\r\n");
      out.write("\t<input type=\"hidden\" id=\"hideLanguageId\" value=\"\"/>\r\n");
      out.write("\t<input type=\"hidden\" id=\"responseEnabled\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.responseEnabled}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t<input type=\"hidden\" id=\"curMessageDate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.rcDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t<input type=\"hidden\" id=\"subject\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.subject}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t<input type=\"hidden\" id=\"accountName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accountName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t<input type=\"hidden\" id=\"pendingTaskNum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rowIndex }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t<!-- 隐藏表单  -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"selectTemplateDiv\" class=\"easyui-dialog\" title=\"请选择模板\" style=\"width:800px;top: 10px;\"\r\n");
      out.write("\t\t\tdata-options=\"\r\n");
      out.write("\t\t\t\ticonCls: 'icon-save',\r\n");
      out.write("\t\t\t\tbuttons: '#dlg-buttons',\r\n");
      out.write("\t\t\t\tmodal:true,closed: true\r\n");
      out.write("\t\t\t\">\r\n");
      out.write("\t\t空\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"dlg-buttons\">\r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"javascript:$('#selectTemplateDiv').dialog('close')\">关闭</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"w\" class=\"easyui-window\" title=\"售后详情\" data-options=\"modal:true,collapsible:false,minimizable:false,maximizable:false,closed:true,iconCls:'icon-save'\" style=\"width:90%;\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"inputRejectInfo\" class=\"easyui-dialog\" title=\"录不良\" data-options=\"\r\n");
      out.write("\t\t\t\ticonCls: 'icon-save',buttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'保存',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-ok',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\tsaveRejectInfo();\r\n");
      out.write("\t\t\t\t\t\t$('#inputRejectInfo').dialog('close');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttext:'关闭',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t$('#inputRejectInfo').dialog('close');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}],modal:true,closed: true\" style=\"width:60%;top: 10px;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"divCancelDeal\" class=\"easyui-dialog\" title=\"取消交易\" data-options=\"\r\n");
      out.write("\t\t\t\ticonCls: 'icon-save',buttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'保存',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-ok',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\tcancelOrder();\r\n");
      out.write("\t\t\t\t\t\t$('#divCancelDeal').dialog('close');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttext:'关闭',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t$('#divCancelDeal').dialog('close');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}],modal:true,closed: true\" style=\"width:60%;top: 10px;\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"cancelOrderId\" value=\"\"/> <!-- 取消交易对应的订单Id -->\t\t\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"cancelOrderGuid\" value=\"\"/>\t\t\r\n");
      out.write("\t\t<table class=\"table table-bordered\" style=\"padding-top: 20px;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><b>买家原因:</b></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"radio\" crid=\"1\" name=\"rdoCancelReason\" class=\"form-control-sm\" text=\"BuyerNoLongerWantsItem\">BuyerNoLongerWantsItem</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t    <td><input type=\"radio\" crid=\"2\" name=\"rdoCancelReason\" class=\"form-control-sm\" text=\"BuyerPurchasingMistake\">BuyerPurchasingMistake</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t    <td><input type=\"radio\" crid=\"3\" name=\"rdoCancelReason\" class=\"form-control-sm\" text=\"ShippingAddressNotConfirmed\">ShippingAddressNotConfirmed</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><b>其他原因:</b></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"radio\" crid=\"4\" name=\"rdoCancelReason\" class=\"form-control-sm\" text=\"SellerDoesntShipToCountry\"/>SellerDoesntShipToCountry</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t<td><input type=\"radio\" crid=\"5\" name=\"rdoCancelReason\" class=\"form-control-sm\" text=\"BuyerReturnedItemForRefund\"/>BuyerReturnedItemForRefund</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t    <td><input type=\"radio\" crid=\"6\" name=\"rdoCancelReason\" class=\"form-control-sm\" text=\"Other reasons\"/>OtherExplanation</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><b>卖家原因:</b></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"radio\" crid=\"7\" name=\"rdoCancelReason\" class=\"form-control-sm\" text=\"SellerRanOutOfStock\"/>SellerRanOutOfStock</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"radio\" crid=\"8\" name=\"rdoCancelReason\" class=\"form-control-sm\" text=\"UnableToResolveTerms\"/>UnableToResolveTerms</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write(" <!-- 修改语言选择div -->\r\n");
      out.write(" <div id=\"upLanguage\" class=\"easyui-dialog\" title=\"请选择语言信息\" data-options=\"\r\n");
      out.write("\t\t\t\ticonCls: 'icon-save',buttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'保存',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-ok',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\tupMssageLanguage();\r\n");
      out.write("\t\t\t\t\t\t$('#upLanguage').dialog('close');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttext:'关闭',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t$('#upLanguage').dialog('close');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}],modal:true,closed: true\" style=\"width:60%;top: 10px;z-index: 9999;\">\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write(" \t<!-- 自定义类别div -->\r\n");
      out.write("\t<div id=\"upCustomDiv\" class=\"easyui-dialog\" title=\"自定义类别信息\" data-options=\"\r\n");
      out.write("\t\t\t\ticonCls: 'icon-save',buttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'保存',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-ok',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\tupMessageCustom();\r\n");
      out.write("\t\t\t\t\t\t$('#upCustomDiv').dialog('close');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttext:'关闭',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t$('#upCustomDiv').dialog('close');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}],modal:true,closed: true\" style=\"width:60%;top: 10px;z-index: 9999;\">\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\t\t\t\t<b>自订类别:</b>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</dl>\r\n");
      out.write(" \t</div>\r\n");
      out.write(" \t\r\n");
      out.write(" \t<!-- 合旧订单 -->\r\n");
      out.write("\t<div id=\"mergeOrder\" class=\"easyui-dialog\" title=\"合旧订单\" data-options=\"\r\n");
      out.write("\t\t\t\ticonCls: 'icon-save',buttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'关闭',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t$('#mergeOrder').dialog('close');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}],modal:true,closed: true\" style=\"width:90%;top: 10px;z-index: 9999;\">\r\n");
      out.write("\t\t<iframe id=\"mergeOrderFrame\" name=\"mergeOrderFrame\" \r\n");
      out.write("\t\t\t\tstyle=\"width: 100%;height: 500px;\" frameborder=\"0\"></iframe>\t\t\r\n");
      out.write(" \t</div>\r\n");
      out.write(" \t\r\n");
      out.write(" \t\r\n");
      out.write(" \t<!-- 待发送发票订单列表 -->\r\n");
      out.write("\t<div id=\"sendInvoiceDailog\" class=\"easyui-dialog\" title=\"待发送发票订单列表\" data-options=\"\r\n");
      out.write("\t\t\t\ticonCls: 'icon-save',buttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'确定',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\tinitInvoiceByGuids();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttext:'关闭',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t$('#sendInvoiceDailog').dialog('close');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}],modal:true,closed: true\" style=\"width:90%;top: 10px;z-index: 9999;\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"emailAddress\" value=\"\"/>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"fromEmail\" value=\"\"/>\r\n");
      out.write("\t\t\t\t<table id=\"orderInfoTableCopy\" title=\"查询结果\" style=\"width:100%;\" \r\n");
      out.write("\t\t\t\t\tclass=\"easyui-datagrid\" data-options=\"singleSelect:false,collapsible:true,\r\n");
      out.write("\t\t\t\t\tautoRowHeight:true,fitColumns:true\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'ck',checkbox:true\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'accountName',width:60,align:'center'\"><b>账号</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'orderId',width:90,align:'center'\"><b>订单号</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'buyerAccount',width:90,align:'center'\"><b>客户账号</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'allTotalPrice',width:50,align:'center'\"><b>总金额</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'isPaidName',width:60,align:'center',formatter: function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif (row.isPaid=='1'){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn '是';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn '否';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\"><b>是否支付</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'paymentTypeName',width:60,align:'center'\"><b>支付方式</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'isSendOffStr',width:70,align:'center',formatter: function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif (row.isSendOff=='1'){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn '是';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn '否';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\"><b>是否导出</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'isPaid',width:60,align:'center',hidden:true\"><b>是否支付</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'address',width:60,align:'center',hidden:true\"><b>address</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'phone',width:60,align:'center',hidden:true\"><b>phone</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'city',width:60,align:'center',hidden:true\"><b>city</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'email',width:60,align:'center',hidden:true\"><b>email</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'province',width:60,align:'center',hidden:true\"><b>province</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'postalcode',width:60,align:'center',hidden:true\"><b>postalcode</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'country',width:70,align:'center',hidden:true\"><b>country</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'postOrderDate',width:70,align:'center',hidden:true\"><b>postOrderDate</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'refundCount',width:70,align:'center',hidden:true\"><b>refundCount</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'mendCount',width:70,align:'center',hidden:true\"><b>mendCount</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'caseCount',width:70,align:'center',hidden:true\"><b>caseCount</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'rejectCount',width:70,align:'center',hidden:true\"><b>rejectCount</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'feedbackCount',width:70,align:'center',hidden:true\"><b>feedbackCount</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'cancelOrderCount',width:70,align:'center',hidden:true\"><b>cancelOrderCount</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'freezeState',width:70,align:'center',hidden:true\"><b>freezeState</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'isSendOff',width:70,align:'center',hidden:true\"><b>isSendOff</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'accountId',width:70,align:'center',hidden:true\"><b>accountId</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'currency',width:70,align:'center',hidden:true\"><b>currency</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'groupInfoId',width:70,align:'center',hidden:true\"><b>groupInfoId</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'paymentPrice',width:70,align:'center',hidden:true\"><b>paymentPrice</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'guid',align:'center',hidden:true\"><b>guid</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'buyerName',align:'center',hidden:true\"><b>buyerName</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'salesPlatformId',align:'center',hidden:true\"><b>salesPlatformId</b></th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t</table>  \r\n");
      out.write(" \t</div>\r\n");
      out.write("<div id=\"maskLayer\" style=\"display: none;width: 100%;  height: 100%\"> \t\r\n");
      out.write("\t<div style=\" position: absolute;  top: 0%;  left: 0%;  width: 100%;  height: 100%; \r\n");
      out.write("\t\t background-color: black;  z-index:9000;  -moz-opacity: 0.7;  opacity:.70;  filter: alpha(opacity=70);\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"z-index:9999;top: 30%;position: absolute;left: 30%;background-attachment: scroll;background-clip: border-box;background-color: #FFF;background-image: none;background-origin: padding-box;background-position: 0% 0%;background-repeat: repeat;background-size: auto auto;border-bottom-color: #000;border-bottom-left-radius: 5px;border-bottom-right-radius: 5px;border-bottom-style: none;border-bottom-width: 0px;border-image-outset: 0 0 0 0;border-image-repeat: stretch stretch;border-image-slice: 100% 100% 100% 100%;border-image-source: none;border-image-width: 1 1 1 1;border-left-color: #000;border-left-style: none;border-left-width: 0px;border-right-color: #000;border-right-style: none;border-right-width: 0px;border-top-color: #000;border-top-left-radius: 5px;border-top-right-radius: 5px;border-top-style: none;border-top-width: 0px;box-shadow: #EDEDED 0px 0px 0px 3px inset, #A2A2A2 0px 0px 0px 1px, rgba(0, 0, 0, 0.15) 0px 0px 20px 0px;font-family: Helvetica,Arial,sans-serif;font-feature-settings: normal;font-kerning: auto;font-language-override: normal;font-size: 10px;font-size-adjust: none;font-stretch: normal;font-style: normal;font-synthesis: weight style;font-variant: normal;font-variant-alternates: normal;font-variant-caps: normal;font-variant-east-asian: normal;font-variant-ligatures: normal;font-variant-numeric: normal;font-variant-position: normal;font-weight: 400;line-height: 10px;margin-bottom: 0px;margin-left: 0px;margin-right: 0px;margin-top: 0px;outline-color: #000;outline-style: none;outline-width: 0px;padding-bottom: 0px;padding-left: 0px;padding-right: 0px;padding-top: 0px;vertical-align: baseline;width: 600px;-moz-border-bottom-colors: none;-moz-border-left-colors: none;-moz-border-right-colors: none;-moz-border-top-colors: none;\">\r\n");
      out.write("\t\t<img src=\"/images/loading.gif\"/><span style=\"font-family: '微软雅黑';font-size: 14px;color: black;\">处理成功,正在自动加载下一封站内信........</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write(" </body> \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /views/communication/CommunicationHandle.jsp(91,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isNewMessage==true }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t<div id=\"commbefore\" class=\"easyui-panel\" title=\"新沟通记录\" \r\n");
        out.write("\t\t\t\t   \t\tdata-options=\"iconCls:'icon-save',collapsible:true,collapsed:true,onBeforeExpand:searchBeforeMessage\" \r\n");
        out.write("\t\t\t\t   \t\tstyle=\"width: 97%;\">\r\n");
        out.write("\t\t\t\t   \t\t<input type=\"hidden\" id=\"beforeTabs_flag\" value=\"0\" />\r\n");
        out.write("\t\t\t\t   \t\t<div id=\"beforeTabs\" class=\"easyui-tabs\" style=\"width:100%\">\r\n");
        out.write("\t\t\t\t   \t\t\t<div id=\"sameOrderBefore\" title=\"同订单沟通记录\">\r\n");
        out.write("\t\t\t\t\t   \t\t\t<div id=\"sameOrderContentBefore\">\r\n");
        out.write("\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t<div id=\"sameCustomBefore\" title=\"同客户沟通记录\" style=\"padding:10px\">\r\n");
        out.write("\t\t\t\t\t\t\t\t<div id=\"sameCustomContentBefore\"></div>\r\n");
        out.write("\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t</div>\t\r\n");
        out.write("\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t   \t<div style=\"height: 5px;\"></div>\r\n");
        out.write("\t\t\t\t   \t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /views/communication/CommunicationHandle.jsp(142,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("receiveAttachment");
    // /views/communication/CommunicationHandle.jsp(142,11) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/views/communication/CommunicationHandle.jsp(142,11) '${messageBean.receiveAttachments }'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${messageBean.receiveAttachments }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t   \t\t\t<div style=\"width: 100px;float:left; height: 64px; border: 1px solid Gray; margin-left:10px;cursor: pointer;\" onclick=\"displayPic(this,");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${receiveAttachment.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\">\r\n");
          out.write("\t\t\t\t\t\t   \t\t\t\t<img width='30' height='40' src='/images/u479.png' alt='' title='点击查看图片'/>\r\n");
          out.write("\t\t\t\t\t\t   \t\t\t\t<span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${receiveAttachment.attachmentName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\t\t\t\t\t\t   \t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t   \t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /views/communication/CommunicationHandle.jsp(187,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("languageInfo");
    // /views/communication/CommunicationHandle.jsp(187,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/views/communication/CommunicationHandle.jsp(187,8) '${lstLanguageInfo }'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${lstLanguageInfo }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"selectTemplate('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${languageInfo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${languageInfo.langName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("模板</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /views/communication/CommunicationHandle.jsp(201,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageBean.responseEnabled==true }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"sendMessage()\" id=\"btnSendMessage\" style=\"width:100px;\">发送</a>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"sendMessage()\" id=\"btnSendMessage\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:100px;\" data-options=\"disabled:true\">发送</a>\r\n");
        out.write("\t\t\t  \t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /views/communication/CommunicationHandle.jsp(401,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("languageInfo");
    // /views/communication/CommunicationHandle.jsp(401,1) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/views/communication/CommunicationHandle.jsp(401,1) '${lstLanguageInfo }'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${lstLanguageInfo }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<input type=\"radio\" name=\"radio\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${languageInfo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${languageInfo.langName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" &nbsp;&nbsp;\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f3.setParent(null);
    // /views/communication/CommunicationHandle.jsp(425,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVar("customState");
    // /views/communication/CommunicationHandle.jsp(425,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/views/communication/CommunicationHandle.jsp(425,3) '${lstCustomState}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${lstCustomState}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
      if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<dd style=\"margin-left: 5px;\">\r\n");
          out.write("\t\t\t\t\t<input type=\"radio\" name=\"customTypeId\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customState.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\tradioText=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customState.customType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customState.customType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("\t\t\t\t</dd>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f3.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
    }
    return false;
  }
}
