/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2015-10-29 12:35:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _7523304b28a24a2b9d01a958b1c71800_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" /><title>订单详情</title></head><body><div align=\"center\" style=\"background:url(bgg.jpg) no-repeat ; background-size: cover; -moz-background-size: cover; \"><table style=\"margin-top: 20px\" align=\"left\" cellpadding=\"5px\" cellspacing=\"0px\" ><tr><td>&nbsp&nbsp采购日期: 2015-10-13</td></tr><tr><td>&nbsp&nbsp订单总数: 1</td></tr><tr><td>&nbsp--------------------------------------</td></tr><tr><td>&nbsp&nbsp采购日期: 2015-10-16</td></tr><tr><td>&nbsp&nbsp订单总数: 1</td></tr><tr><td>&nbsp--------------------------------------</td></tr><tr><td>&nbsp&nbsp采购日期: 2015-10-19</td></tr><tr><td>&nbsp&nbsp订单总数: 1</td></tr><tr><td>&nbsp--------------------------------------</td></tr><tr><td>&nbsp&nbsp采购日期: 2015-10-20</td></tr><tr><td>&nbsp&nbsp订单总数: 1</td></tr><tr><td>&nbsp--------------------------------------</td></tr><tr><td>&nbsp&nbsp采购日期: 2015-10-22</td></tr><tr><td>&nbsp&nbsp订单总数: 1</td></tr><tr><td>&nbsp--------------------------------------</td></tr><tr><td>&nbsp&nbsp采购日期: 2015-10-25</td></tr><tr><td>&nbsp&nbsp订单总数: 1</td></tr><tr><td>&nbsp--------------------------------------</td></tr><tr><td>&nbsp&nbsp采购日期: 2015-10-26</td></tr><tr><td>&nbsp&nbsp订单总数: 7</td></tr><tr><td>&nbsp--------------------------------------</td></tr><tr><td>&nbsp&nbsp采购日期: 2015-10-27</td></tr><tr><td>&nbsp&nbsp订单总数: 2</td></tr><tr><td>&nbsp--------------------------------------</td></tr><tr><td>&nbsp&nbsp采购日期: 2015-10-28</td></tr><tr><td>&nbsp&nbsp订单总数: 4</td></tr><tr><td>&nbsp--------------------------------------</td></tr><tr><td>&nbsp&nbsp采购日期: 2015-10-29</td></tr><tr><td>&nbsp&nbsp订单总数: 5</td></tr><tr><td>&nbsp--------------------------------------</td></tr><tr><td>详情请登录浩方供应商门户<br>http://sp.hofan.cn/<br></td></tr><br></table></body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
